// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    name: string;
    account_type: AccountType;
    institution_name: string;
    account_mask?: (string | null);
    base_currency?: string;
    notes?: (string | null);
    is_active?: boolean;
};

export type AccountPublic = {
    name: string;
    account_type: AccountType;
    institution_name: string;
    account_mask?: (string | null);
    base_currency?: string;
    notes?: (string | null);
    is_active?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

export type AccountType = 'brokerage' | 'bank';

export type AuditEventPublic = {
    id: string;
    entity_type: string;
    entity_id: string;
    event_type: string;
    source_record_id?: (string | null);
    transform_version?: (string | null);
    changed_fields?: (string | null);
    created_at: string;
};

export type AuditEventsPublic = {
    data: Array<AuditEventPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ConnectorSyncResponse = {
    source: string;
    status: string;
    snapshot_version: string;
    synced_records: number;
    normalized_records: number;
    conflict_records: number;
};

export type HealthReportResponse = {
    week: string;
    generated_at: string;
    positions_count: number;
    total_market_value_usd: number;
    asset_class_count: number;
    anomaly_count: number;
    stale: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PortfolioCreate = {
    name: string;
    account_id: string;
    description?: (string | null);
    is_active?: boolean;
};

export type PortfolioPublic = {
    name: string;
    account_id: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type PortfoliosPublic = {
    data: Array<PortfolioPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnifiedPortfolioResponse = {
    snapshot_version: string;
    stale: boolean;
    data: Array<UnifiedPosition>;
};

export type UnifiedPosition = {
    symbol: string;
    asset_class: string;
    quantity: number;
    market_value_usd: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsReadAccountsData = {
    includeInactive?: boolean;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PortfolioSyncConnectorPositionsData = {
    accountId: string;
    source: string;
};

export type PortfolioSyncConnectorPositionsResponse = (ConnectorSyncResponse);

export type PortfolioGetUnifiedPortfolioData = {
    accountId?: (string | null);
    portfolioId?: (string | null);
};

export type PortfolioGetUnifiedPortfolioResponse = (UnifiedPortfolioResponse);

export type PortfolioGetHealthReportData = {
    accountId?: (string | null);
    portfolioId?: (string | null);
};

export type PortfolioGetHealthReportResponse = (HealthReportResponse);

export type PortfolioGetAuditEventsResponse = (AuditEventsPublic);

export type PortfoliosCreatePortfolioData = {
    requestBody: PortfolioCreate;
};

export type PortfoliosCreatePortfolioResponse = (PortfolioPublic);

export type PortfoliosReadPortfoliosData = {
    includeInactive?: boolean;
};

export type PortfoliosReadPortfoliosResponse = (PortfoliosPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);