/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPortfolioRouteImport } from './routes/_layout/portfolio'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPortfolioIndexRouteImport } from './routes/_layout/portfolio.index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutPortfolioConflictsRouteImport } from './routes/_layout/portfolio.conflicts'
import { Route as LayoutPortfolioAuditRouteImport } from './routes/_layout/portfolio.audit'
import { Route as LayoutAdminAssetsRouteImport } from './routes/_layout/admin.assets'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioRoute = LayoutPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioIndexRoute = LayoutPortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPortfolioRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutPortfolioConflictsRoute =
  LayoutPortfolioConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => LayoutPortfolioRoute,
  } as any)
const LayoutPortfolioAuditRoute = LayoutPortfolioAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutPortfolioRoute,
} as any)
const LayoutAdminAssetsRoute = LayoutAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/portfolio': typeof LayoutPortfolioRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/admin/assets': typeof LayoutAdminAssetsRoute
  '/portfolio/audit': typeof LayoutPortfolioAuditRoute
  '/portfolio/conflicts': typeof LayoutPortfolioConflictsRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/portfolio/': typeof LayoutPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/assets': typeof LayoutAdminAssetsRoute
  '/portfolio/audit': typeof LayoutPortfolioAuditRoute
  '/portfolio/conflicts': typeof LayoutPortfolioConflictsRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/portfolio': typeof LayoutPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/portfolio': typeof LayoutPortfolioRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/assets': typeof LayoutAdminAssetsRoute
  '/_layout/portfolio/audit': typeof LayoutPortfolioAuditRoute
  '/_layout/portfolio/conflicts': typeof LayoutPortfolioConflictsRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/portfolio/': typeof LayoutPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/portfolio'
    | '/settings'
    | '/admin/assets'
    | '/portfolio/audit'
    | '/portfolio/conflicts'
    | '/admin/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/items'
    | '/settings'
    | '/'
    | '/admin/assets'
    | '/portfolio/audit'
    | '/portfolio/conflicts'
    | '/admin'
    | '/portfolio'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/portfolio'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/assets'
    | '/_layout/portfolio/audit'
    | '/_layout/portfolio/conflicts'
    | '/_layout/admin/'
    | '/_layout/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio': {
      id: '/_layout/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof LayoutPortfolioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/': {
      id: '/_layout/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof LayoutPortfolioIndexRouteImport
      parentRoute: typeof LayoutPortfolioRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/portfolio/conflicts': {
      id: '/_layout/portfolio/conflicts'
      path: '/conflicts'
      fullPath: '/portfolio/conflicts'
      preLoaderRoute: typeof LayoutPortfolioConflictsRouteImport
      parentRoute: typeof LayoutPortfolioRoute
    }
    '/_layout/portfolio/audit': {
      id: '/_layout/portfolio/audit'
      path: '/audit'
      fullPath: '/portfolio/audit'
      preLoaderRoute: typeof LayoutPortfolioAuditRouteImport
      parentRoute: typeof LayoutPortfolioRoute
    }
    '/_layout/admin/assets': {
      id: '/_layout/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof LayoutAdminAssetsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAssetsRoute: typeof LayoutAdminAssetsRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAssetsRoute: LayoutAdminAssetsRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutPortfolioRouteChildren {
  LayoutPortfolioAuditRoute: typeof LayoutPortfolioAuditRoute
  LayoutPortfolioConflictsRoute: typeof LayoutPortfolioConflictsRoute
  LayoutPortfolioIndexRoute: typeof LayoutPortfolioIndexRoute
}

const LayoutPortfolioRouteChildren: LayoutPortfolioRouteChildren = {
  LayoutPortfolioAuditRoute: LayoutPortfolioAuditRoute,
  LayoutPortfolioConflictsRoute: LayoutPortfolioConflictsRoute,
  LayoutPortfolioIndexRoute: LayoutPortfolioIndexRoute,
}

const LayoutPortfolioRouteWithChildren = LayoutPortfolioRoute._addFileChildren(
  LayoutPortfolioRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPortfolioRoute: typeof LayoutPortfolioRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPortfolioRoute: LayoutPortfolioRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
